// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIaWqllThbrLFp4oUyqzePgpOnMvjyip0',
    appId: '1:1076941031873:android:60a2b86acb62986b6d4740',
    messagingSenderId: '1076941031873',
    projectId: 'ttwigo-86d8d',
    storageBucket: 'ttwigo-86d8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLp1N7E0rStiPD5xS67AmOdJtyBZk6Vz4',
    appId: '1:1076941031873:ios:eec61a6af73784356d4740',
    messagingSenderId: '1076941031873',
    projectId: 'ttwigo-86d8d',
    storageBucket: 'ttwigo-86d8d.firebasestorage.app',
    iosBundleId: 'com.example.ttwigo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIRt7OopRFR0BfjE3T4YgvcHv2nYOrwwo',
    appId: '1:1076941031873:web:128c782cb0b95abe6d4740',
    messagingSenderId: '1076941031873',
    projectId: 'ttwigo-86d8d',
    authDomain: 'ttwigo-86d8d.firebaseapp.com',
    storageBucket: 'ttwigo-86d8d.firebasestorage.app',
    measurementId: 'G-JRCBJXV4GL',
  );

}